name: liveness_detection_sdk
description: A comprehensive Flutter SDK for liveness detection with face tracking
version: 0.0.1
homepage: https://github.com/AniketGharat/liveness_detection_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0
  path_provider: ^2.1.1
  path: ^1.8.3
  permission_handler: ^10.2.0
  vibration: ^1.7.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2