name: liveness_detection_sdk
description: A comprehensive Flutter SDK for liveness detection with face tracking
version: 0.0.1
homepage: https://github.com/AniketGharat/liveness_detection_sdk

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0  # Keep this for face detection
  google_ml_kit: ^0.16.3  # Upgrade google_ml_kit to a compatible version
  path_provider: ^2.1.1
  path: ^1.8.3
  synchronized: ^3.0.0
  image: ^3.0.1
  async: ^2.10.0
  provider: ^6.0.4  # For state management
  permission_handler: ^10.2.0  # For permission handling
  vibration: ^1.7.3  # For vibration feedback

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
